<a href="https://colab.research.google.com/github/iishikawalia/Numpy-Learning/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
random_tenssor=torch.rand(7)
random_tenssor

tensor([0.7795, 0.5998, 0.0020, 0.2961, 0.2056, 0.6660, 0.1366])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [8]:
# Create another random tensor
import torch
tensor1=torch.rand(1,7)
print(tensor1)
tensor2=torch.rand(1,7).T
print(tensor2)
# Perform matrix multiplication
tensor_mul=torch.matmul(tensor1,tensor2)
print("matmal:\n",tensor_mul)
print("tensor1*tensor2:\n", tensor1*tensor2.T)



tensor([[0.0100, 0.9472, 0.0831, 0.6423, 0.5644, 0.1175, 0.6421]])
tensor([[0.9260],
        [0.2636],
        [0.6110],
        [0.5217],
        [0.2576],
        [0.4695],
        [0.5716]])
matmal:
 tensor([[1.2124]])
tensor1*tensor2:
 tensor([[0.0093, 0.2497, 0.0508, 0.3351, 0.1454, 0.0552, 0.3671]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [10]:
# Set manual seed
import torch
torch.manual_seed(0)
# Create two random tensors
tensor1=torch.rand(1,7)
print(tensor1)
tensor2=torch.rand(1,7).T
print(tensor2)
# Matrix multiply tensors
tensor_mul=torch.matmul(tensor1,tensor2)
print("matmal:\n",tensor_mul)
print("tensor1*tensor2:\n", tensor1*tensor2.T)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
tensor([[0.8964],
        [0.4556],
        [0.6323],
        [0.3489],
        [0.4017],
        [0.0223],
        [0.1689]])
matmal:
 tensor([[1.1173]])
tensor1*tensor2:
 tensor([[0.4449, 0.3500, 0.0559, 0.0461, 0.1235, 0.0142, 0.0828]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [11]:
# Set random seed on the GPU
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [16]:
# Set random seed
import torch
torch.manual_seed(1234)

# Check for access to GPU
device="cuda" if torch.cuda.is_available() else "cpu"
print(f"device:{device}")
# Create two random tensors on GPU
tensor1 = torch.rand((2, 3)).to(device)
tensor2 = torch.rand((2, 3)).to(device)
print(tensor1,"\n", tensor2)

device:cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') 
 tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [18]:
# Perform matmul on tensor_A and tensor_B
mmul=torch.matmul(tensor1,tensor2.T)
mmul

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [20]:
# Find max
print(torch.max(mmul))
# Find min
print(torch.min(mmul))

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [21]:
# Find arg max
torch.argmax(mmul)
# Find arg min
torch.argmin(mmul)

tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [22]:
# Set seed
import torch
torch.manual_seed(7)
# Create random tensor
tensor1=torch.rand(1,1,1,10)
print(f"tensor1: {tensor1}")
print(f"tensor1 shape: {tensor1.shape}")

# Remove single dimensions
tensor2=tensor1.squeeze()

# Print out tensors and their shapes
print(tensor1, tensor1.shape)
print(tensor2, tensor2.shape)

tensor1: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor1 shape: torch.Size([1, 1, 1, 10])
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
