<a href="https://colab.research.google.com/github/iishikawalia/Machine-Learning/blob/main/model4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
X = torch.tensor([[1.0],[2.0],[3.0],[4.0]],dtype=torch.float32)
y = torch.tensor([[1.0],[4.0],[7.0],[10.0]],dtype=torch.float32)

In [3]:
model=nn.Linear(1,1)
loss_fn=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)

In [6]:
epochs=1000
for epoch in range(epochs):
  model.train()
  y_pred=model(X)
  loss=loss_fn(y_pred,y)
  loss.backward()
  optimizer.step()
  optimizer.zero_grad()
  if epoch%100==0:
    print(f"epoch {epoch}: loss = {loss.item():.4f}")

epoch 0: loss = 38.6031
epoch 100: loss = 0.6750
epoch 200: loss = 0.3706
epoch 300: loss = 0.2034
epoch 400: loss = 0.1117
epoch 500: loss = 0.0613
epoch 600: loss = 0.0337
epoch 700: loss = 0.0185
epoch 800: loss = 0.0101
epoch 900: loss = 0.0056


In [7]:
print(model.parameters)
print(model.weight)
print(model.bias)

<bound method Module.parameters of Linear(in_features=1, out_features=1, bias=True)>
Parameter containing:
tensor([[2.9540]], requires_grad=True)
Parameter containing:
tensor([-1.8647], requires_grad=True)


In [8]:
with torch.inference_mode():
    print(model(X))

tensor([[1.0893],
        [4.0433],
        [6.9972],
        [9.9512]])
